language: java

jdk:
  - oraclejdk8
  - openjdk8

addons:
  sonarcloud:
    organization: "thecheerfuldev-github"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar